#pragma once
#include "wincompat.h"

#define Button_GetCheck(window) ((UINT)SendMessage((window), BM_GETCHECK, 0, 0))
#define Button_SetCheck(window, check) ((void)SendMessage((window), BM_SETCHECK, (WPARAM)(check), 0))
#define Button_Enable(window, enable) EnableWindow((window), (enable))
#define Static_SetText(window, text) SetWindowText((window), (text))
#define Edit_SetText(window, text) SetWindowText((window), (text))
#define Edit_GetText(window, text, size) GetWindowText((window), (text), (size))
#define Edit_LimitText(window, limit) ((void)SendMessage((window), EM_SETLIMITTEXT, (WPARAM)(limit), 0))
#define Edit_SetSel(window, first, last) ((void)SendMessage((window), EM_SETSEL, (WPARAM)(first), (LPARAM)(last)))
#define ComboBox_AddString(window, text) ((int)SendMessage((window), CB_ADDSTRING, 0, (LPARAM)(LPCSTR)(text)))
#define ComboBox_DeleteString(window, index) ((int)SendMessage((window), CB_DELETESTRING, (WPARAM)(index), 0))
#define ComboBox_GetCount(window) ((int)SendMessage((window), CB_GETCOUNT, 0, 0))
#define ComboBox_GetCurSel(window) ((int)SendMessage((window), CB_GETCURSEL, 0, 0))
#define ComboBox_FindString(window, start, text) ((int)SendMessage((window), CB_FINDSTRING, (WPARAM)(start), (LPARAM)(LPCSTR)(text)))
#define ComboBox_SetCurSel(window, index) ((int)SendMessage((window), CB_SETCURSEL, (WPARAM)(index), 0))
#define ComboBox_GetItemData(window, index) ((LRESULT)SendMessage((window), CB_GETITEMDATA, (WPARAM)(index), 0))
#define ComboBox_SetItemData(window, index, data) ((int)SendMessage((window), CB_SETITEMDATA, (WPARAM)(index), (LPARAM)(data)))
#define ComboBox_GetLBText(window, index, text) ((int)SendMessage((window), CB_GETLBTEXT, (WPARAM)(index), (LPARAM)(LPSTR)(text)))
#define ComboBox_ResetContent(window) ((void)SendMessage((window), CB_RESETCONTENT, 0, 0))
#define ComboBox_GetDroppedControlRect(window, rectangle) ((BOOL)SendMessage((window), CB_GETDROPPEDCONTROLRECT, 0, (LPARAM)(rectangle)))
#define ListBox_AddString(window, text) ((int)SendMessage((window), LB_ADDSTRING, 0, (LPARAM)(LPCSTR)(text)))
#define ListBox_InsertString(window, index, text) ((int)SendMessage((window), LB_INSERTSTRING, (WPARAM)(index), (LPARAM)(LPCSTR)(text)))
#define ListBox_DeleteString(window, index) ((int)SendMessage((window), LB_DELETESTRING, (WPARAM)(index), 0))
#define ListBox_GetCount(window) ((int)SendMessage((window), LB_GETCOUNT, 0, 0))
#define ListBox_GetCurSel(window) ((int)SendMessage((window), LB_GETCURSEL, 0, 0))
#define ListBox_GetSel(window, index) ((int)SendMessage((window), LB_GETSEL, (WPARAM)(index), 0))
#define ListBox_SetSel(window, selected, index) ((int)SendMessage((window), LB_SETSEL, (WPARAM)(selected), (LPARAM)(index)))
#define ListBox_SetTopIndex(window, index) ((int)SendMessage((window), LB_SETTOPINDEX, (WPARAM)(index), 0))
#define ListBox_FindStringExact(window, start, text) ((int)SendMessage((window), LB_FINDSTRINGEXACT, (WPARAM)(start), (LPARAM)(LPCSTR)(text)))
#define ListBox_SetCurSel(window, index) ((int)SendMessage((window), LB_SETCURSEL, (WPARAM)(index), 0))
#define ListBox_GetItemData(window, index) ((LRESULT)SendMessage((window), LB_GETITEMDATA, (WPARAM)(index), 0))
#define ListBox_SetItemData(window, index, data) ((int)SendMessage((window), LB_SETITEMDATA, (WPARAM)(index), (LPARAM)(data)))
#define ListBox_GetText(window, index, text) ((int)SendMessage((window), LB_GETTEXT, (WPARAM)(index), (LPARAM)(LPSTR)(text)))
#define ListBox_ResetContent(window) ((void)SendMessage((window), LB_RESETCONTENT, 0, 0))

#define GET_X_LPARAM(value) static_cast<int>(static_cast<SHORT>(LOWORD(value)))
#define GET_Y_LPARAM(value) static_cast<int>(static_cast<SHORT>(HIWORD(value)))
